name: NewRelic Daily Metrics to Sheets

on:
  schedule:
    - cron: '50 23 * * *' # Run at 23:50 UTC
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  collect-daily-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd nr-metrics-to-sheets
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Google Service Account
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}' | base64 -d > service_account.json
      - name: Run APM metrics collection
        run: python fetch_nr.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      - name: Run error logs collection
        run: |
          cd nr-metrics-to-sheets
          python fetch_nr_err_logs.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      - name: Run host metrics collection
        run: |
          cd nr-metrics-to-sheets
          python fetch_nr_hosts.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      - name: Run 5XX Errors
        run: |
          cd nr-metrics-to-sheets
          python fetch_nr_5XX_errors.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
