name: NewRelic Weekly Metrics to Sheets

on:
  schedule:
    - cron: '55 23 * * 6' # Run at 23:55 UTC on Saturdays
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-weekly-metrics-errorlogs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          cd nr-metrics-to-sheets
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup Google Service Account
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_BASE64 }}' | base64 -d > service_account.json
      - name: Run weekly APM metrics collection
        run: |
          python nr-metrics-to-sheets/fetch_nr_weekly.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      - name: Run weekly host metrics collection
        run: |
          python nr-metrics-to-sheets/fetch_nr_hosts_weekly.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      - name: Run weekly error logs collection
        run: |
          python nr-metrics-to-sheets/fetch_nr_err_logs_weekly.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json
      - name: Run weekly 5XX errors collection
        run: |
          python nr-metrics-to-sheets/fetch_nr_5XX_errors_weekly.py
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: service_account.json